### ISSUE TITLE
Can't talk to water fountain

### ISSUE THREAD

**Issue by corporategoth** [RobertD502/home-assistant-petkit#10]
I am seeing this in the logs consistently:

```
2023-05-12 21:57:31.342 WARNING (MainThread) [custom_components.petkit] Got petkit device detail for Cat Water failed: {'error': {'code': 97, 'msg': 'App is out of date, please upgrade'}}
```

**Comment by RobertD502** [comment]
Couple of things...can you confirm what water fountain model you have.

Also, out of curiosity can you confirm that it is this integration that you're using and not the one from https://github.com/hasscc/petkit

I've never had this error logged in my integration - Only when using the integration from the other repo above.

**Comment by RobertD502** [comment]
[Upon further investigation](https://github.com/hasscc/petkit/blob/4edbc0676660bc98f2d78af50b97d16b3e075426/custom_components/petkit/__init__.py#L409) it looks like you are indeed using the other person's repo/integration and not this one based on the exact warning being logged.

If you want to use this integration, you'll have to delete the other individual's integration and download the code from my repo/go through the setup process described in the documentation - One thing is for sure though, water fountains work for this integration, including controlling them, if you have the bluetooth relay set up in the petkit app.

**Comment by corporategoth** [comment]
Quite right ... I'll fix that up :)

**Comment by RobertD502** [comment]
For a second you had me questioning if I was in fact logging such a warning, but no worries at all!
