### ISSUE TITLE
Way to use a secondary account

### ISSUE THREAD

**Issue by egormanga** [RobertD502/home-assistant-petkit#100]
Apparently, contrary to what the docs say, there's a way to use a second account for the integration while still being able to use both the app and HA.

The steps are somewhere along the lines of the following:
1. Set up all devices on the primary account;
2. Log in with the primary account credentials via the HA integration;
3. Log in back in the mobile app, then create an invitation link for the family/home;
4. Register a new account for HA using the invitation link, joining the family;
5. Without deleting it, press «Reconfigure» on the integration auth popup and now enter the secondary credentials instead.

Now all the parsed entities should remain there, but will be updated using the secondary account. They wouldn't be detected by logging in with the second account, but they won't disappear when changing the account without deleting the config entry.

That's how I use it now and, for me, it works.

**Comment by RobertD502** [comment]
Correct, I added that in one of the latest releases, but forgot to redo the documentation - some features for certain devices will be missing if using a secondary account just because of limits placed by PetKit on secondary accounts. You may not experience this based on what devices you have.
