### ISSUE TITLE
Invalid authentication error

### ISSUE THREAD

**Issue by meanandpinchy** [RobertD502/home-assistant-petkit#103]
I had this set up with my Fresh Element Solo feeder, and it worked great. I accidentally logged into the app (to change the feeder name) without logging out in HA because I'd forgot about their stupid one-device limitation, and when I looked in HA again, it said that the integration required re-authentication. I made sure I was logged out in the app, then entered my username, password, and country (US). I got the error "Invalid authentication. Are your credentials correct?" Restarted HA and tried again, same thing. Removed and re-downloaded the integration, tried again, same thing. I've tried off and on over a couple of days, but always the same thing. I knew the credentials were correct, but just in case it might shake something loose, I logged into PetKit on my computer and changed my password, then tried again. Same thing. I'm not logged in with the app (I cleared the app cache and data, and even powered off my phone), or with the computer, but I still get that same error. I typed my username and password with one finger to make absolutely sure I was entering them correctly. I don't know what else to do.

**Comment by RobertD502** [comment]
Have you checked the home assistant logs for anything aside from the error that pops up in the UI when you're configuring the integration?

**Comment by meanandpinchy** [comment]
I did see one earlier, but it just said that the login was invalid. I can log in successfully using that email and password on my computer, and in the app.

**Comment by RobertD502** [comment]
If you could share the credentials with me via a private message on discord (same username as here), I can attempt to figure out what is going on.
