### ISSUE TITLE
Add support for Fresh Element Gemini

### ISSUE THREAD

**Issue by eduardoribeiro** [RobertD502/home-assistant-petkit#14]
I own a Fresh Element Gemini, which is pretty much the same as Fresh Element Solo, the difference is that has a different id and thus doesn't show up on the integration (id: 'd4s')... I was about to create a collaboration by opening a PR on this repo and at `petkitaio` repo but I'm not able to... I've made all the changes locally but since I don't have access to `petkitaio` it still doesn't work

**Comment by RobertD502** [comment]
Shoot me a message on discord and I'll direct you on how to get the petkitaio dependency changed to your repo/complete testing.
