### ISSUE TITLE
Not able to install the repository

### ISSUE THREAD

**Issue by alexpelli** [RobertD502/home-assistant-petkit#17]
Hi.. I'm trying to install the repository but no way. I'm not much experienced with HA.. 
Could you help me?
Thanks

**Comment by RobertD502** [comment]
Do you have HACS installed?

**Comment by alexpelli** [comment]
Hello.. thank you for your reply.

 

Actually I have:

Home Assistant 2023.6.2

Supervisor 2023.06.2

Operating System 10.3

Frontend 20230608.0 – latest

 

Installed in raspberry P4

 

 

 

Da: Dr. Drinovac ***@***.***> 
Inviato: sabato 24 giugno 2023 06:25
A: RobertD502/home-assistant-petkit ***@***.***>
Cc: alexpelli ***@***.***>; Author ***@***.***>
Oggetto: Re: [RobertD502/home-assistant-petkit] Not able to install the repository (Issue #17)

 

Do you have HACS installed?

**Comment by RobertD502** [comment]
But do you have HACS [(Home assistant community store)](https://hacs.xyz) installed?

If not, I'd recommend reading up on how to install HACS and how to add custom repositories into HACS / use it in general.

You shouldn't have a problem - there are plenty of guides out there.

**Comment by alexpelli** [comment]
I don’t have… I don’t have.. I will look for instructions and install itIl giorno 26 giu 2023, alle ore 07:34, Dr. Drinovac ***@***.***> ha scritto:﻿
But do you have HACS (Home assistant community store) installed?
If not, I'd recommend reading up on how to install HACS and how to add custom repositories into HACS / use it in general.
You shouldn't have a problem - there are plenty of guides out there.
