### ISSUE TITLE
Petkit fresh element 6L

### ISSUE THREAD

**Issue by floco** [RobertD502/home-assistant-petkit#19]
Hello

Great integration :-) I have this one for a while. Do you think it would be possible to support it ?
https://petkit.us/products/petkit-element-wi-fi-enabled-smart-pet-food-container-feeder
Currently the integration only send back number.cat_set_weight

Thanks a lot

**Comment by RobertD502** [comment]
Send me a personal message on discord (you can find me in the petkit discord server). I'll need access to the account to identify the internal model given to the feeder by PetKit as well as what options are available.

**Comment by floco** [comment]
Thanks @RobertD502  ! 
This is so great :-)
