### ISSUE TITLE
Add support for China region

### ISSUE THREAD

**Issue by ProphetRush** [RobertD502/home-assistant-petkit#22]
Hello, 
    Thanks for your work. Could you add a support for China region? The corresponsding api address is 'http://api.petkit.cn/6/'.

**Comment by ProphetRush** [comment]
Also the username for China region is phone number with country code like 86-XXXXXXXXXXX

**Comment by RobertD502** [comment]
This uses the new PetKit API which is `http://api.petktasia.com/latest` for PetKit Asia accounts (including China according to their server response). You should be able to log in by making sure the PetKit Asia account option is checked when sending your username/password.

**Comment by ProphetRush** [comment]
I've tried multiple times but sadly it doesn't work. Keep telling me 'The phone is not registered'. Once I modify the code inside petkitaio package I can login successfully.

**Comment by RobertD502** [comment]
I see. So I'm assuming only Hong Kong accounts use e-mail/password which is what the servers are saying to use the `http://api.petktasia.com/latest` endpoint for. In that case, I will have to add yet another option to both petkitaio and Home Assistant.

What devices are you integrating?

**Comment by ProphetRush** [comment]
Pura MAX Litter Box~

**Comment by RobertD502** [comment]
> Pura MAX Litter Box~

Were you able to control it using petkitaio (send commands)?

**Comment by RobertD502** [comment]
Great! In that case I'll get the changes made on both ends.

**Comment by ProphetRush** [comment]
Thank you so much! Have a great day~!

**Comment by RobertD502** [comment]
@ProphetRush Update to the latest release (`0.1.7`) and select the `PetKit China account` during setup to use the China region base API URL.

**Comment by RobertD502** [comment]
@ProphetRush Can you sniff out traffic using the latest petkit app? Curious to see if China accounts are still using the China region base url.

Their region list has both China and Hong Kong as `https://api.petktasia.com/latest/`, but that didn't work before for China accounts. They may have switched over (they switched EU accounts to a different endpoint) and I'll need to make sure the base URL is correct for you in the next update I push out.

**Comment by ProphetRush** [comment]
> 

OK, I'll when I have some time, been super busy at work these days :(

**Comment by ProphetRush** [comment]
> 

Yes, the China accounts are still remains in current api

**Comment by RobertD502** [comment]
> > 
> 
> 
> 
> Yes, the China accounts are still remains in current api

Great! I went ahead and set the library to use the China API if a user selects the China region instead of the PETKIT Asia API, which their server region endpoint says to use but is wrong. So, 0.1.8 should work for you without a problem.

**Comment by ProphetRush** [comment]
OK, thanks!
