### ISSUE TITLE
Cannot Log in "The phone number is not registered"

### ISSUE THREAD

**Issue by davidvalasek** [RobertD502/home-assistant-petkit#29]
Hello, can you help me what I'm doing wrong? It's first time I log in.

This error originated from a custom integration.

Logger: custom_components.petkit
Source: custom_components/petkit/util.py:41 
Integration: PetKit (documentation, issues) 

Unknown PetKit Error: PetKit Error 125: The phone number is not registered

**Comment by RobertD502** [comment]
What country are you located in?

**Comment by davidvalasek** [comment]
Europe/Czech Republic

**Comment by RobertD502** [comment]
Related to #28.

PetKit changed the API and I am currently working on a fix.
