### ISSUE TITLE
 Adding Petkit pura max

### ISSUE THREAD

**Issue by Starcon79** [RobertD502/home-assistant-petkit#3]
Hello, I have a Petkit pura max. I was hoping that it would also be recognized because it has the same functions as the Petkit pura x. But unfortunately she is not found. I only get one device for my cat. Is it possible to add the Petkit pura max? Would be really great.

**Comment by RobertD502** [comment]
That is the correct behavior as this integration only pulls in devices that are currently in the list of supported devices. I am trying to keep the integration clean and focused on devices that have been tested and not just pulling in any PetKit device as this will only lead to more issues.

I can work with you to get the Pura Max integrated, but have to warn you I don't have time at this moment. You can reach out to me on the discord server for this integration and we can work from there - [invite link](https://discord.gg/wuDRm62V)

**Comment by RobertD502** [comment]
Commenting to keep open as this is still in progress

**Comment by alexmorbo** [comment]
Any news about this litter?

**Comment by RobertD502** [comment]
Still in progress. You can stay up to date by joining the discord channel.

**Comment by alexmorbo** [comment]
Invite link expired, can you give new?
