### ISSUE TITLE
No devices found

### ISSUE THREAD

**Issue by giobuc** [RobertD502/home-assistant-petkit#34]
Hi, thank you for your compontent!!! 

I have a Fresh Element Mini Pro and a Pura X.... I created a new account, as indicated in the instructions, via the Petkit app and shared the two devices.
The new user, through the app, is able to use the devices normally.

If I create the integration in Home Assistant with the new user data, the "no devices found" error appears, while if I create the integration with the original user data I have all my devices available.

How is this possible?
Thank you :)

**Comment by RobertD502** [comment]
This is due to the family share feature that PETKIT introduced. If you use the app with the new account you'll see that the devices are located under a different header and not returned as part of the account's device roster.

**Comment by RobertD502** [comment]
> Thanks for such a quick reply 🙂
> 
> 
> 
> It works perfectly!!!  
> 
> 
> 
> Thanks again 🙂

No problem! I'll have to edit the documentation to make mention of this since they started utilizing the "Family share" feature.
