### ISSUE TITLE
Virtual Machine without TZ variable

### ISSUE THREAD

**Issue by Anian-igor** [RobertD502/home-assistant-petkit#37]
Hello.
I've trying to setup PetKit but got well known issue regarding timezone TZ variable
I've setup HassOS on virtual machine on Proxmox and don't have any TZ variable on it. Just a regula Home assistant operation system.
How I can fix an issue?
I already tried to create manual file with timezone (like on a pure debian) and TZ variable but without luck.

**Comment by RobertD502** [comment]
If you are using Home Assistant OS then ensure you have a timezone setup within the Home Assistant settings: found under Settings --> System --> General.

**Comment by Anian-igor** [comment]
Yes. Timezone installed at start but I still have an issue.

**Comment by RobertD502** [comment]
Please post any logs associated with PETKIT. I'm not sure if I'll be able to help much, but if you have any backups I'd recommend reverting back to before you started to tinker with manually trying to set up a timezone on the operating system.

**Comment by Anian-igor** [comment]
`2023-09-12 17:37:24.720 ERROR (MainThread) [custom_components.petkit] A timezone could not be found. If you are running Home Assistant as a standalone Docker container, you must define the TZ environmental variable.`
I started with installation and trying to add something manually on a test instance.

**Comment by RobertD502** [comment]
> `2023-09-12 17:37:24.720 ERROR (MainThread) [custom_components.petkit] A timezone could not be found. If you are running Home Assistant as a standalone Docker container, you must define the TZ environmental variable.`
> 
> I started with installation and trying to add something manually on a test instance.

How did you install Home assistant on Proxmox? Was the Home Assistant OS image used to create a VM or was another operating system installed with Home Assistant on top of it as a supervised method or docker method or even pyenv? The timezone error doesn't happen with Home Assistant OS installs.

**Comment by Anian-igor** [comment]
Home assistant OS VM on proxmox. Not docker or supervised method

**Comment by RobertD502** [comment]
In that case, this is the first I've heard of it happening. I don't have a solution on hand. If this is a test environment, I'd recreate the VM and start from scratch.

**Comment by Anian-igor** [comment]
This is a production environment. I don't want to recreate. I think I need to forget about Petkit service at least for some time.

**Comment by RobertD502** [comment]
If you can get into the command line of the OS (not the Home Assistant CLI) and execute the command `cat /etc/timezone`, a valid timezone should be in that file.

The Home Assistant CLI has `ha` in the terminal - if you see this then you are **not** in the OS's terminal:
![image](https://github.com/RobertD502/home-assistant-petkit/assets/52541649/46fdf9d2-c55d-40ac-b370-ae041c8907c5)

Example of output from Home Assistant OS's terminal output for the command above:

![image](https://github.com/RobertD502/home-assistant-petkit/assets/52541649/2790b91b-4f76-47c6-8d51-ff0c261760e4)

**Comment by Anian-igor** [comment]
![зображення](https://github.com/RobertD502/home-assistant-petkit/assets/5881313/2b65f74d-6daf-48c2-aa49-8ef33484243a)

**Comment by RobertD502** [comment]
What happens when you run `ls -l /etc/localtime`

**Comment by RobertD502** [comment]
Also, run the command `ha info` and let me know the output of that (there should be a timezone listed).

**Comment by Anian-igor** [comment]
ha info
![зображення](https://github.com/RobertD502/home-assistant-petkit/assets/5881313/3f0e94b8-0261-4b4f-8534-4e09c53268a1)
docker container inspect homeassistant
`"Env": [
                "SUPERVISOR=172.30.32.2",
                "HASSIO=172.30.32.2",
                "TZ=Europe/Kyiv",
`
cat /etc/timezone - absent after reboot

**Comment by RobertD502** [comment]
cat /etc/timezone absent after a reboot? That should not be the case. The cat /etc/timezone command is looking at the OS's timezone configuration which should always be there.

**Comment by Anian-igor** [comment]
It's to complicated to me to resolve an issue.

**Comment by RobertD502** [comment]
Hi, I think I tracked down the problem. It looks like the `tzlocal` library doesn't recognize the `Europe/Kyiv` timezone, only `Europe/Kiev`. I don't see the latter as in option in Home Assistant. In order to fix that, the tzlocal library maintainer will need to push out an update to include your timezone. I've created a bug report on that project and hopefully it will be fixed.

In the meantime, if you can switch your Home Assistant to another timezone that is identical to `Europe/Kyiv` and valid with the tzlocal library, that should get you going.

**Comment by RobertD502** [comment]
I see that both `Europe/Kyiv` and `Europe/Riga` observe the same time offset and Daylight savings time schedule. If you want to use this integration without waiting on the maintainer to fix the tzlocal library, you can change your timezone to `Riga` via the Home Assistant GUI and that should get the integration running.

**Comment by Anian-igor** [comment]
> @Anian-igor I see that both `Europe/Kyiv` and `Europe/Riga` observe the same time offset and Daylight savings time schedule. If you want to use this integration without waiting on the maintainer to fix the tzlocal library, you can change your timezone to `Riga` via the Home Assistant GUI and that should get the integration running.

I tried Europe\Riga and reboot home assistant host but without luck.
`2023-09-22 19:03:25.830 ERROR (MainThread) [custom_components.petkit] A timezone could not be found. If you are running Home Assistant as a standalone Docker container, you must define the TZ environmental variable.`

**Comment by RobertD502** [comment]
> > @Anian-igor I see that both `Europe/Kyiv` and `Europe/Riga` observe the same time offset and Daylight savings time schedule. If you want to use this integration without waiting on the maintainer to fix the tzlocal library, you can change your timezone to `Riga` via the Home Assistant GUI and that should get the integration running.
> 
> I tried Europe\Riga and reboot home assistant host but without luck. `2023-09-22 19:03:25.830 ERROR (MainThread) [custom_components.petkit] A timezone could not be found. If you are running Home Assistant as a standalone Docker container, you must define the TZ environmental variable.`
In your `configuration.yaml` file add `tzlocal: debug` to the `logger`. Save the file and then restart Home Assistant. Open the full Home Assistant log and there should be logging done by tzlocal in there. Share that here.

**Comment by Anian-igor** [comment]
It's a strange. I changed timezone in configuration but docker inspect still show Kyiv timezone.
Also in logs
`2023-09-22 19:25:55.149 DEBUG (MainThread) [tzlocal] Found a TZ environment: Europe/Kyiv
2023-09-22 19:25:55.149 DEBUG (MainThread) [tzlocal] TZ does not contain a time zone name`

**Comment by RobertD502** [comment]
Did you press update on the bottom of the page after changing the timezone in the HA GUI?

**Comment by RobertD502** [comment]
You wouldn't happen to have time_zone set in your configuration.yaml file? If so, then setting it in the GUI won't work.

**Comment by Anian-igor** [comment]
I tried to setup via configuration.yaml but this still didn't help

**Comment by RobertD502** [comment]
Did you remove time_zone from configuration.yaml, save the file, and restart Home Assistant before attempting to set the time zone via the GUI?

**Comment by Anian-igor** [comment]
Yes. Remove from configuration. Reboot and shutdown host to be sure. Still didn't help. Europe/Kyiv via inspector.

**Comment by RobertD502** [comment]
I'd raise an issue on the Home Assistant Core repo, since this seems to be a bug of its own. Perhaps they will be able to help get to the bottom of your time zone not changing when set via the GUI.

**Comment by RobertD502** [comment]
@Anian-igor 

I am currently putting together a Timezone option for the configuration flow where you'll be able to select `Europe/Kyiv` as the timezone instead of relying on the tzlocal library to fetch the timezone from Home Assistant (which fails since tzlocal doesn't have Europe/Kyiv in its list of timezones). This way you won't have to change your timezone in Home Assistant and we don't have to wait on the tzlocal library maintaner to update his code.

Once the new version of this integration is release, update to it and you should see the option to select a timezone during setup.

**Comment by Anian-igor** [comment]
Ready to start testing ASAP. Thanks a lot

**Comment by RobertD502** [comment]
@Anian-igor Upgrade to version `0.1.10` and select `Europe/Kyiv` as your timezone during the integration setup.
