### ISSUE TITLE
TZ issue

### ISSUE THREAD

**Issue by Alyangula** [RobertD502/home-assistant-petkit#38]
Hey @RobertD502 ,

Thanks for this.

I'm a bit of a noob at python, but i had a look through the code and cannot see where it might be getting stuck.

Not sure if its something to do with my location but i seem to have everything required set..

i'm running HA in a container on my QNAP.
installed HACS user this method: 
![image](https://github.com/RobertD502/home-assistant-petkit/assets/58903108/453b9b84-d4b5-4975-ba14-4ec99db479f0)
have environment variables set:
inside container terminal
![image](https://github.com/RobertD502/home-assistant-petkit/assets/58903108/1bd0e0ab-2c9a-49b3-a0db-b219f4add19b)
in container settings within QNAP:
![image](https://github.com/RobertD502/home-assistant-petkit/assets/58903108/48c2a884-0024-48d6-9788-94b7a94b1a70)
Timezone is set in HA:
![image](https://github.com/RobertD502/home-assistant-petkit/assets/58903108/59a5a1b7-0613-4da2-8872-263f9cc9f05f)

Logs:
2023-09-13 05:12:10.033 ERROR (MainThread) [custom_components.petkit] A timezone could not be found. If you are running Home Assistant as a standalone Docker container, you must define the TZ environmental variable.

let me know if you need any more details or how i can further troubleshoot.

**Comment by RobertD502** [comment]
In your configuration.yaml for debugging set `tzlocal: debug`, save it. Restart home assistant and then try doing it again. After it fails your full HA logs should have some debugging from the tzlocal library.

**Comment by RobertD502** [comment]
Nevermind, I see your issue. That isn't a correct TZ you have set. It should be `Australia/Darwin` NOT `Darwin/Australia`.

**Comment by Alyangula** [comment]
.....thanks. lol. apologies for wasting your time.

Did you just look that up here or something? https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

working now:
![image](https://github.com/RobertD502/home-assistant-petkit/assets/58903108/070e1cf8-5ecd-48e1-8ec3-50f05e2acfd4)
