### ISSUE TITLE
A timezone could not be found

### ISSUE THREAD

**Issue by cybersea54** [RobertD502/home-assistant-petkit#39]
I'm running **Home Assistant 2023.9.2 Supervisor 2023.09.2 Operating System 10.5 Frontend 20230911.0 - latest**, not a Docker version, but still getting this error when try to setup integration. 

```
Logger: custom_components.petkit
Source: custom_components/petkit/util.py:34
Integration: PetKit ([documentation](https://github.com/RobertD502/home-assistant-petkit/blob/main/README.md), [issues](https://github.com/RobertD502/home-assistant-petkit/issues))
First occurred: 14:28:37 (2 occurrences)
Last logged: 14:36:08
A timezone could not be found. If you are running Home Assistant as a standalone Docker container, you must define the TZ environmental variable.
```

TZ environment variable presents in system:

![изображение](https://github.com/RobertD502/home-assistant-petkit/assets/10558685/fce42cf9-e85a-44a1-982e-4fad0803210c)

**Comment by RobertD502** [comment]
Can you please run the command `cat /etc/timezone`. This will provide the timezone that Home Assistant OS has defined. You'll need to be within the Home Assistant OS shell terminal when running the command. The env command you ran returns what the TZ variable is set to within the docker container that resides inside of the OS.

**Comment by cybersea54** [comment]
Here is output from Home Assistant OS, it seems time zone didn't set:
![изображение](https://github.com/RobertD502/home-assistant-petkit/assets/10558685/a5f4b4fc-fa67-41d8-91a1-c43b04ca5d68)
There is full logs:
```
2023-09-22 13:11:09.575 DEBUG (MainThread) [tzlocal] Found a TZ environment: Asia/Ho_Chi_Minh
2023-09-22 13:11:09.575 DEBUG (MainThread) [tzlocal] TZ does not contain a time zone name
```
There is python output:
![изображение](https://github.com/RobertD502/home-assistant-petkit/assets/10558685/ae7dec57-69f1-4827-8db2-adadd5183fd8)

**Comment by RobertD502** [comment]
Home Assistant OS does have a timezone set (Etc/UTC), so there is no issue there.

This seems to be a bug with the tzlocal library. Based on their code, the reason it is failing is because Asia/Ho_Chi_Minh is missing from their [list](https://github.com/regebro/tzlocal/blob/61bec506713a2e51abaf1f4f210bcdf84ecfa7c2/tzlocal/windows_tz.py#L148). So, this isn't anything wrong on your end, rather, a missing timezone in their code.

**Comment by RobertD502** [comment]
I raised an issue with the maintainer of the library, but until that is fixed on their end and a new version of tzlocal is pushed out, the `Asia/Ho_Chi_Minh` timezone won't work. I do see that the `Asia/Bangkok` timezone has the same offset as `Asia/Ho_Chi_Minh` - In the meantime, if you set your timezone to `Bangkok` via the Home Assistant GUI, you should be able to use this integration.

**Comment by RobertD502** [comment]
Disregard the comment above. I am working on implementing a Timezone option in the configuration flow where you'll be able to select `Asia/Ho_Chi_Minh` as an option - this way you won't have to change your timezone in Home Assistant and we don't have to wait on the tzlocal library maintainer to update his code.

**Comment by RobertD502** [comment]
@cybersea54 Upgrade to version `0.1.10` and select `Asia/Ho_Chi_Minh` as your timezone during the integration setup.
