### ISSUE TITLE
Yumshare Compatibility - Upgraded Gemini

### ISSUE THREAD

**Issue by Thecat8413** [RobertD502/home-assistant-petkit#43]
So the new Yumshare Dual Hopper shipped, and we just got it in and set up. Currently it's not compatible with the integration, but as it's essentially an upgraded version of a Gemini, I was hoping it would be possible to expand the same feature set to it without much effort. Either way, thank you for your work on this integration, it's been a huge help.

**Comment by wja731** [comment]
I have access to the Yumshare dual hopper if needed for testing

**Comment by Thecat8413** [comment]
> I have access to the Yumshare dual hopper if needed for testing

@wja731 

I have already provided access to mine, although if you would like to help I'm sure @RobertD502 would appreciate having another example.

**Comment by RobertD502** [comment]
Sorry everyone. Haven't had a lot of time, but still getting it done!

**Comment by LvWind** [comment]
There is another repository supported the Yumshare Dual Hopper feeder(d4s), but it's not maintained anymore.
Check these commits may help you.
https://github.com/hasscc/petkit/commit/70d8f8527ae0623296558d3cbd22a64b20902cbc
https://github.com/hasscc/petkit/commit/4edbc0676660bc98f2d78af50b97d16b3e075426
