### ISSUE TITLE
Cat weight 

### ISSUE THREAD

**Issue by ilianhris** [RobertD502/home-assistant-petkit#45]
Hello. I can't see the most important sensor in puramax "cat weight". Is it there?

**Comment by RobertD502** [comment]
Please see the [documentation](https://github.com/RobertD502/home-assistant-petkit#pets). The cat weight is located in a sensor under a separate device in Home Assistant.

**Comment by ilianhris** [comment]
Hello. I checked all sensors under integration but can see only Litter weigh. Can you  be more specific how can find that sensor.
Thank You.
> 
![IMG_1914](https://github.com/RobertD502/home-assistant-petkit/assets/112797248/6c6ce680-3c07-4a91-9ed0-8e57d3327e1e)
![IMG_1913](https://github.com/RobertD502/home-assistant-petkit/assets/112797248/394c0f87-af3f-4fd7-91be-211b88ef7da0)

**Comment by ilianhris** [comment]
I figured it out. Was used shared account and not showing watter and cat.
Thank again.
