### ISSUE TITLE
PETKIT Stainless Steel Cat Water Fountain

### ISSUE THREAD

**Issue by ilianhris** [RobertD502/home-assistant-petkit#46]
Is that device supported PETKIT Stainless Steel Cat Water Fountain
Thanks.

**Comment by RobertD502** [comment]
The litter boxes can act as a BLE relay. Setting up the relay is done inside of the PetKit mobile app - please reference PetKit's information regarding this as it is outside of the scope of this integration (this integration isn't officially sponsored by PetKit).
