### ISSUE TITLE
Avatar URLs

### ISSUE THREAD

**Issue by willliamchan** [RobertD502/home-assistant-petkit#47]
Hi there

Thank you so much for making this and this is something that I've been waiting for so long!

Just a quick question about my pet's avatar, is it possible to script the avatar to use https instead of http?

I am getting this and I tried to add http(s) and the picture loads too.

![image](https://github.com/RobertD502/home-assistant-petkit/assets/54702221/d64efddc-0718-4593-aed4-bb3f29c7f918)

On the other hand, is there a way to keep weight history? The value seems reset every once in a while, and I'd like to always know what is the last measured weight of my cats.

**Comment by RobertD502** [comment]
Can't use https. Petkit's API uses http.

Regarding weight - the next update will include a method to retain weight measurements if a particular day hasn't had any litter box usage yet.

**Comment by RobertD502** [comment]
Easiest way to check is to take the url and replace it with https - if you can fetch the image from your browser with https then it is possible. However, I know that using the API itself (controlling devices) won't work with https as I've tried.
