### ISSUE TITLE
Support for YumShare Solo

### ISSUE THREAD

**Issue by ydogandjiev** [RobertD502/home-assistant-petkit#49]
Hello, thank you for the great integration! It's very easy to setup and works really well. I do wonder if you can add support for the YumShare Solo feeder that Petkit just recently released:
https://petkit.com/products/yumshare-solo-with-camera

I just bought one on Black Friday but it doesn't show up as one of the my devices when I configure this integration. My Eversweet Solo 2 and cats showed up without any issue so I know the integration is configured correctly. If you need any help getting the API data for the device, please let me know how to collect the necessary information.

Thanks again for building this helpful integration!

**Comment by RobertD502** [comment]
Thanks for the support! You aren't mistaken, the feeder isn't supported yet - work is currently in progress for the dual hopper version of the Yum share, but I'll work on getting the solo supported as well. Once I have more time, I'll need to sniff out the communication for the solo to get it integrated.

* Just so I don't get your hopes up, I have to break it to you that the yumshare camera won't be supported due to how they deliver the video stream. PETKIT uses the Agora platform to deliver live streams, which isn't supported by Home Assistant camera entities.

**Comment by xswxm** [comment]
one more thing, the video clips can also be downloaded from the cloud directly (up to 1~2 days) even without subscriptions, the encryption method of the video files is quite easy to be decrypted. However, the live stream, i believe petkit uses tencent xp2p technology, and its pks canbe extracted from the protcols. However, it definetly need more work to make it work without the petkit app.

Another,,,,,,, the petkit feeders use Ingenic T31 chips, which means we can flash the openipc firmware into these machines, but there will another bunch of work to make the wifi & ble chips to work.  And I am not good at it.

**Comment by Cyrelion** [comment]
Hello,

is there any update on the Yumshare Solo support? Would be great to get this supported. Video isn’t highly required, the normal sensors and triggering feeding would be absolutely enough for me.

**Comment by Jezza34000** [comment]
Hi !
What's new about this feeder support ? I got one, i can help...

**Comment by Cyrelion** [comment]
I‘ve got a dual hopper now. So anything new?

**Comment by Jezza34000** [comment]
I've try the version from @xswxm and it work very well. Did you work on it from this last .zip version ?
What do you plan for DS4h support @RobertD502 ? Any help wanted to work on some feature ?

**Comment by hyperfive** [comment]
I would be willing to contribute / sponsor someone to get the yum dual hopper working

**Comment by RobertD502** [comment]
> I would be willing to contribute / sponsor someone to get the yum dual hopper working 

Dual hopper is being worked on at the moment. Check out the discord development channel where I just shared an update.

**Comment by shenmirenQUQ** [comment]
> @RobertD502为什么不直接修改 petkitaio 模块并将其直接合并到此集成中。因为某些设备类型，如 d4sh（与 d4s 相同，在中国名称不同），不包含在 petkitaio 模块中。而且，我相信大多数设备共享相同的协议并具有相似的 json 结构。
> 
> 这是我修改后的版本，增加了对 d4sh 设备和中文翻译的支持 [。petkit.zip](https://github.com/RobertD502/home-assistant-petkit/files/13541331/petkit.zip)

你好，d4sh是solo那个型号的吗?

**Comment by ivorsmorenburg** [comment]
Hopefully is supported soon! 🥳🥳🤓

**Comment by Cyrelion** [comment]
I moved to https://github.com/Jezza34000/home-assistant-petkit and currently working with him on supporting the Litterbox ULTRA too.

**Comment by ayhanboy** [comment]
I was waiting for this for a long time. Why this is closed? Is this coming soon?

**Comment by Jezza34000** [comment]
This was closed because of "stale". Anyway don't wait anymore it's available here : https://github.com/Jezza34000/homeassistant_petkit
