### ISSUE TITLE
very sporadic updates 

### ISSUE THREAD

**Issue by steuerzentrale** [RobertD502/home-assistant-petkit#53]
Hi there

first of all many thanks for this niece piece of software. I have a Petkit Eversweet 3 Pro. I **dont** own any Petkit smart feeder which acts as a BLE-gateway. I installed your integration and it works well so far. I created two accounts in the Petkit app. One for the integration with HA. From this account I shared the device to the second account which I am using inside the app.

Now to my question: The **filter** and **water-level** only get updated when I open the app and wait like 1-2 minutes. If I dont open the app, these sensors dont get updated. For example when I dont open the app for 1 week, the sensor called "last data update" shows the last update 1 week ago and nor the filter or water-level sensors get updated.

The sensor for the purified water and energy-usage however get updated like every 5 hours or so.

Is this an expected behaviour due to the way the app works?

Petkit Eversweet 3 Pro firmware 2.49
Petkit integration v0.1.10

HA
Core 2024.1.5
Supervisor 2023.12.1
Operating System 11.4
Frontend 20240104.0

all the best

Andrew

**Comment by RobertD502** [comment]
That is the correct behavior. As stated in the documentation:

```
Note #1: Getting the most recent data from your water fountain, as well as controlling the water fountain, requires that the BLE relay is set up within the PetKit app. Otherwise, you will be limited to data that isn't up-to-date and no ability to control the water fountain as it requires another compatible PetKit device acting as a BLE relay.
```
