### ISSUE TITLE
Eversweet Max support

### ISSUE THREAD

**Issue by yzlnew** [RobertD502/home-assistant-petkit#58]
It seems only available in China currently.

**Comment by RobertD502** [comment]
Please elaborate as to what the issue is.

**Comment by yzlnew** [comment]
I’m thinking about buying it, but I haven‘t because of the Spring Festival. If I receive it, I can provide my account or other information.

**Comment by RobertD502** [comment]
> I’m thinking about buying it, but I haven't because of the Spring Festival. If I receive it, I can provide my account or other information.

I'm unable to use a Chinese account - I use the international PETKIT app and I believe for Chinese accounts there is a separate PETKIT app that is specific for mainland China.

If you can link me to the product page, I can take a look and see if it is the same water fountain that is available internationally, but just with a different name.

**Comment by yzlnew** [comment]
Here's [link](https://m.tb.cn/h.5tbxezDMvGfZRG8?tk=XyFmW9I8714) to the Taobao Petkit store. But it requires an account to see detailed product information. 
Product image from Google search [here](https://www.google.com/imgres?imgurl=https%3A%2F%2Fimg12.360buyimg.com%2Fn1%2Fjfs%2Ft1%2F249620%2F30%2F3806%2F55821%2F65b7d3e6F7836b516%2F3eec087f7845f495.jpg&tbnid=kkNHx89I0CDL7M&vet=1&imgrefurl=https%3A%2F%2Fwww.jd.com%2Fxinkuan%2F69943fdc05094a6ae667.html&docid=hmvTXVxoMJE4zM&w=350&h=350&hl=zh-hans-us&source=sh%2Fx%2Fim%2Fm1%2F3&kgs=a4cdbd71da05898b). 
Or we can just wait its global release.

**Comment by RobertD502** [comment]
Oh yeah, that is definitely not currently being sold here yet. If control of the water fountain is different than the current ones, then that will require reverse engineering their code like I had to do for the current water fountains (this is a very time-consuming process). The bluetooth water fountains (via the BLE relay) aren't controlled by simple commands sent to the API. You have to build the commands from scratch involving creating byte lists, bit shifting, etc which is then b64 encoded. Someone that owns the water fountain will have to go through this process of reverse engineering how petkit creates command messages for this water fountain, if it is different from the current water fountains. 

So, I wouldn't go buying the water fountain in hopes of it being supported by the integration - support will only come if someone else has this water fountain and decides to dedicate the time to reverse engineering the communication.

**Comment by hyperfive** [comment]
Hello

this unit is available in the US and I just ordered one. I’m happy to use mine to test to get integration working. Please let me know what I can do to help.

**Comment by RobertD502** [comment]
> Hello
> 
> 
> 
> this unit is available in the US and I just ordered one. I’m happy to use mine to test to get integration working. Please let me know what I can do to help. 

I looked at the manual once it was available in the US and saw that it has some different options and modes compared to the current water fountains.

I personally won't be working on supporting the fountain - getting the other water fountains integrated required a lot of reverse engineering of how the Bluetooth messages are constructed. Given the different modes available in this model, the same will have to be done.

As to how anyone can help: I'm open to accepting code in the backend library for anyone that spends the time reverse engineering the communication for the new water fountain.

**Comment by Hedda** [comment]
FYI, the Eversweet Max is now sold on Amazon in the US and in Europe.
