### ISSUE TITLE
Missing "Adsorption Enhance" switch

### ISSUE THREAD

**Issue by sliwma** [RobertD502/home-assistant-petkit#60]
Hi, so at least for PuraMax litter box there's an additonal switch for "adsorption enchance" which is missing from the integration.

**Comment by RobertD502** [comment]
That option must have been added by PETKIT after support was added for the Pura Max to this integration.

I don't have access to a Pura Max, so, only way for me to add a switch for that function is by getting access to one.

**Comment by sliwma** [comment]
Oh, I must have missed your reply. How can I help?

**Comment by nicoodeimos** [comment]
I have a Pura MAX if you guys need help.

**Comment by sliwma** [comment]
I can either share the litterbox in the app, or provide any details required - just let me know.

**Comment by override80** [comment]
In the API response after polling, the setting is named 'bury'. It is at the same level of deepClean, so I guess it could be implemented like the LBDeepCleaning class (could it be something like: LBAdsorptionEnhance?). It's a bool as well.

I can try to implement it and submit a PR after testing.

**Comment by RobertD502** [comment]
> In the API response after polling, the setting is named 'bury'. It is at the same level of deepClean, so I guess it could be implemented like the LBDeepCleaning class (could it be something like: LBAdsorptionEnhance?). It's a bool as well.
> 
> 
> 
> I can try to implement it and submit a PR after testing.
> 
> 

I have a user I am working with this weekend on some other parts of the integration and will look into it then.

**Comment by override80** [comment]
PR is here: https://github.com/RobertD502/home-assistant-petkit/pull/64.

Tested locally, it's working.

**Comment by override80** [comment]
I think it is still actual

**Comment by sliwma** [comment]
Bump.
