### ISSUE TITLE
Eversweet energy usage

### ISSUE THREAD

**Issue by Theetjuh** [RobertD502/home-assistant-petkit#61]
Hi Robert,

I am starting to fill in my individual devices to track energy usage and I saw something weird.

![image](https://github.com/RobertD502/home-assistant-petkit/assets/16882588/3fea5369-5c2b-4600-a09b-7df574ed02e1)

Is this something that can be solved?
I noticed this for quite a while, but since it wasn't that important not really an issue.

HA: 2024.3.0
TZ: Europe/Amsterdam

**Comment by RobertD502** [comment]
Can you provide images of the energy usage dashboard (for the eversweet energy usage entity) along with the history graph from the energy usage entity itself so that I can compare the two for the same timeframe.

**Comment by Theetjuh** [comment]
Sorry, I've been away for a long weekend.

I have rolled back to 2024.2.5 because of snmp issues, so I can't really create the same screenshot since that has been introduced in 2024.3.0

I hope this helps, since the time is 00:01:18 instead of 00:00:00 (I guess)
![image](https://github.com/RobertD502/home-assistant-petkit/assets/16882588/006f0d3b-9c55-4f59-be0c-a6c9b1cf0375)

**Comment by RobertD502** [comment]
Based on the history graph, the entity is working as expected. Looks to be an issue with Home Assistant's energy dashboard.

**Comment by RobertD502** [comment]
Can confirm it is an issue with the Energy Dashboard:

![image](https://github.com/RobertD502/home-assistant-petkit/assets/52541649/e5d9c48a-a4f7-48e1-8ba2-d4fb10a56baf)
![image](https://github.com/RobertD502/home-assistant-petkit/assets/52541649/d37013df-d3c8-4eb8-9f1a-4d8588f89040)

My best guess is that the Energy Dashboard doesn't know how to properly display values that are as low as those provided by the water fountain energy sensor (e.g., 0.0086 kwh) and it ends up reporting the values as negative on the Energy Dashboard. If you really care about it, I'd open an issue in the [Home Assistant Frontend repo](https://github.com/home-assistant/frontend).

**Comment by Theetjuh** [comment]
I am using a Shelly since last week, that measures all the appliances in the kitty room at the moment, that way I can switch the power off/on when one of the devices is unresponsive, so for me it’s not an issue anymore.
