### ISSUE TITLE
Update Discord invitation link please.

### ISSUE THREAD

**Issue by karaminder** [RobertD502/home-assistant-petkit#65]
Currently the join link is, "invalid."

**Comment by RobertD502** [comment]
Based on the server settings and the link used in the readme file, the Discord join link is still active:

![image](https://github.com/RobertD502/home-assistant-petkit/assets/52541649/c7b11d1b-bad7-4a9e-a095-a252b549d586)

![image](https://github.com/RobertD502/home-assistant-petkit/assets/52541649/88bfdffe-96be-4eed-b4d3-63ba0dc23351)

What error are you seeing?
