### ISSUE TITLE
HA restart causes the feeder solo to trigger the meal function

### ISSUE THREAD

**Issue by lifetimr** [RobertD502/home-assistant-petkit#67]
Both the HA device upgrade and restart will cause the feeder solo to trigger the feeding function.

**Comment by RobertD502** [comment]
Do you have an automation set up for the feeder?

**Comment by lifetimr** [comment]
The upgrade only means HA host devices, and does not include petkit devices.i have an automation set up for the feeder.
A virtual button was created via node-red to sync to HomeKit to control the feeder's temporary feeding.

**Comment by RobertD502** [comment]
Disable any automations related to the feeder in both Home Assistant and node red and I think you'll find that it won't happen.

After that, you'll need to rework whatever logic you are using and determine why commands are getting sent during your scenarios.

**Comment by lifetimr** [comment]
thanks
