### ISSUE TITLE
Hack for local control

### ISSUE THREAD

**Issue by Triskae** [RobertD502/home-assistant-petkit#69]
Has anyone tried to open the litter and tried to dump the microcontroller ?
My router advertise it as Espressif, so it may be "powered" by esp or something like that.
I have a Pura MAX, but  no skills at all regarding fw dump, so if anyone has the courage to reverse engineer it, I can help ! 😄

**Comment by RobertD502** [comment]
Sorry to do this, but this is reserved for issues/bugs related to the integration. If you'd like to have a discussion regarding modifying the firmware, it is best suited to open up a discussion on the Home Assistant community forums (you'll be able to reach a lot more people there too).
