### ISSUE TITLE
support for petkit yumshare dual-hopper with camera

### ISSUE THREAD

**Issue by danibiza** [RobertD502/home-assistant-petkit#70]
Hello, I have purchased the Petkit yumshare dual-hopper with camera and I would like to know if it would be possible to integrate it. Thank you so much!

**Comment by RobertD502** [comment]
![image](https://github.com/RobertD502/home-assistant-petkit/assets/52541649/41f9425f-98cd-45dc-a33d-a2c0bdcbc582)

I am currently working on it.
