### ISSUE TITLE
Config flow could not be loaded: {"message":"Invalid handler specified"

### ISSUE THREAD

**Issue by accountant73** [RobertD502/home-assistant-petkit#71]
When trying to add Petkit in integrations I get this error, I have reinstallend and rebooted and cleared cache. Any ideas?

**Comment by accountant73** [comment]
That's okay, last resort is going to be deleting Home assistant and
reinstall through Docker.

Version:

   - Core2024.3.3
   - Frontend20240307.0

From logs:
Logger: homeassistant.config_entries
Source: config_entries.py:2444
First occurred: 16:06:48 (2 occurrences)
Last logged: 17:52:49

Error occurred loading flow for integration petkit: No module named
'petkitaio'

Op di 28 mei 2024 17:49 schreef Dr. Drinovac ***@***.***>:

**Comment by RobertD502** [comment]
I'm not sure how Home Assistant handles requirements when installed via SNAP, but it looks like it didn't install the requirement that is listed in the manifest of the integration (petkitaio). I'd highly recommend ditching the SNAP install and spinning HA up in a docker container instead. Even better, if you are running Proxmox, spin up the HA OS as its own VM so you can add the benefit of snapshots/full VM backups.

**Comment by accountant73** [comment]
Guess it was inevitable haha! Thanks for checking for me!
