### ISSUE TITLE
PetKit Error 97: App is out of date, please upgrade

### ISSUE THREAD

**Issue by AlexW75** [RobertD502/home-assistant-petkit#72]
Hello,

since today i receive a message that the app is out of date.

Logger: custom_components.petkit
Quelle: helpers/update_coordinator.py:347
Integration: PetKit (Dokumentation, Probleme)
Erstmals aufgetreten: 08:35:15 (1 Vorkommnisse)
Zuletzt protokolliert: 08:35:15

Error fetching petkit data: PetKit Error 97: App is out of date, please upgrade

**Comment by RobertD502** [comment]
I received it as well, but just like yourself it was only logged once which indicates that it could have been a temporary error from the servers. The integration still works and it hasn't been logged since.
