### ISSUE TITLE
Statistic for food eaten on Fresh element Infinity

### ISSUE THREAD

**Issue by landaisbenj** [RobertD502/home-assistant-petkit#82]
Hello.

I would to tracks the weight of food consumed by my cat by day. (like app).

So i would like to create a statistic graph on dashboard that can retrieve the daily total sum of food consumed and showing the total amount of food eaten by my cat each day, similar to the energy dashboard.

However, the base entity does not currently allow me to select the sum (cf pic). The only available options are max, min, and average. I believe this might be related to a long-term statistics parameter, but I am not certain.
![image](https://github.com/user-attachments/assets/3e16e433-916a-4ba3-92c7-549c1e18154c)

Could you please tell how or if the long term statistic calculation option can be dev on entity ?
https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics

**Comment by RobertD502** [comment]
Change [this line](https://github.com/RobertD502/home-assistant-petkit/blob/main/custom_components/petkit/sensor.py#L1199) in your local file located at `custom_components/petkit/sensor.py` to `SensorStateClass.TOTAL_INCREASING`.

**Comment by landaisbenj** [comment]
Ok thank you. I try, and i think i need another data, so time to wait my cat eat.

**Comment by landaisbenj** [comment]
> Change [this line](https://github.com/RobertD502/home-assistant-petkit/blob/main/custom_components/petkit/sensor.py#L1199) in your local file located at `custom_components/petkit/sensor.py` to `SensorStateClass.TOTAL_INCREASING`.
> 
> Save the change and then restart Home Assistant for the change to take effect.

Work well, thanks you !!
