### ISSUE TITLE
Pura Max

### ISSUE THREAD

**Issue by lelez84** [RobertD502/home-assistant-petkit#9]
Hi Robert and thank you SO MUCH for your work. I managed to install, despite not knowing Ha, your integration. it accepts my credentials but I can't find anything in entity, only now I think I understand that this is due to the fact that I have a pure max. is it correct in your opinion? do you plan to release an update soon? is this why i can't find entities on Ha? thank you very much!!!

**Comment by RobertD502** [comment]
Only devices that are supported at the moment (listed at the beginning of the repo) will show up in Home Assistant. If you have devices associated with your account that are on the supported list of devices and they aren't showing up then that is an issue. If you only have the Pura Max on your account then no devices are expected to show up at this time...That will change once integrating the Pura Max has been finished.

**Comment by lelez84** [comment]
Perfect! then you are our only hope! thanks thanks thanks I'm going to
donate ;) I look confident ;)

Il giorno dom 30 apr 2023 alle 22:00 Dr. Drinovac ***@***.***>
ha scritto:
