### ISSUE TITLE
[REQUEST] Expose PuraMax 2 cat weight as a sensor

### ISSUE THREAD

**Issue by carpii** [RobertD502/home-assistant-petkit#94]
One of the reasons I bought the PuraMax was for automated weighing of my cat each time it uses the litter box.

But it seems the device doesnt properly expose this as a sensor, and instead just shows it in the app as a text notification (each time the cat uses the device)

Is there a way for these notification messages to be forwarded to HA somehow, so I can try to parse the pet weight out of the text message?

I'm using the new PuraMAX 2, but apart from a few physical changes, I think its pretty much the same as PuraMax 1.

<ins>**App Screenshot**</ins>

![App Screenshot](https://i.imgur.com/JRSti5M.png)

**Comment by Jezza34000** [comment]
It's already possible.

On the petikit integration you have a device that represents your cat. And this representation includes an entity that gives you the weight of your cat. If you have activated the automatic weight change reporting, this entity will allow you to have the information

**Comment by carpii** [comment]
I hadn't spotted that. Very cool, thankyou
